import { chromium } from "@playwright/test";
const b = await chromium.launch({ headless: true });
const p = await b.newPage();
p.on("pageerror", e => console.log("PAGEERROR:", String(e).slice(0,500)));
p.on("console", m => console.log("CONSOLE", m.type() + ":", m.text().slice(0,400)));
p.on("requestfailed", r => console.log("REQFAIL:", r.url(), r.failure()?.errorText));
await p.goto("http://localhost:5182/");
await p.waitForTimeout(8000);
console.log("spike:", JSON.stringify(await p.evaluate(() => window.__spike ?? null)));
console.log("status:", await p.textContent("#status").catch(e => "ERR " + e.message.slice(0,80)));
await b.close();
